### ISSUE TITLE
How end to end setup the Coturn?

### ISSUE THREAD

**Issue by Novienzi** [gjovanov/roomler#10]
hey, good afternoon from here. Do you mind if explain to me how to set up the coturn in development and production mode? Why I always end "TURN server doesn't work" when I test it on the link you recommended for. Or, what I have to do so I got these env parameters : 
TURN_URL=turn:your_coturn_url?transport=udp
TURN_USERNAME=your_coturn_username
TURN_PASSWORD=your_coturn_password

Thanks.

**Comment by gjovanov** [comment]
For starting roomler app, you need to have all these service started:
- mongo
- redis
- coturn
- janus

It's explaine in the [docs](https://github.com/gjovanov/roomler/tree/master/docs) how to start each of them.

e.g. when starting [coturn](https://github.com/gjovanov/roomler/blob/master/docs/deps-coturn.md) you are passing your own params:
- --cli-password=MyTopSecret
- --user=SuperUser:MyTopSecret 
- --server-name=your_domain
- --realm=your_domain

So your coturn needs to be accessible from the internet, hence you pass the `your_domain`.

Then you use `.env.example` to rename it to `.env` and put in there the values of:
- `TURN_URL=turn:your_coturn_url?transport=udp` - whereat `your_coturn_url` must match `your_domain` from coturn params
- `TURN_USERNAME=your_coturn_username` - whereat `your_coturn_username` must match `SuperUser` from coturn params
- `TURN_PASSWORD=your_coturn_password` - whereat `your_coturn_password` must match `MyTopSecret` from coturn params

**Comment by Novienzi** [comment]
Okey, thanks. I'll try it.

**Comment by gjovanov** [comment]
Closing then... Feel free to reopen in case of an issue.
