### ISSUE TITLE
NGINX ERROR

### ISSUE THREAD

**Issue by Novienzi** [gjovanov/roomler#11]
![error nginx](https://user-images.githubusercontent.com/72146793/105346208-d99ed380-5c17-11eb-9c02-23fd88b97055.png)

I already use two public IP in my VM, but still got this error.

**Comment by gjovanov** [comment]
Something is not right with your IP addresses:

- http://geoiplookup.net/ip/52.230.123.253 (Singapore)
- http://geoiplookup.net/ip/20.188.186.146 (Australia)

how is it possible that u have IP address from 2 diff country mapped to a single VM?

Are you sure they are mapped to your VM?

BTW for simplification, you can remove the nginx2 service... It's only needed if you want to server on 443 both COTURN (UDP) and JANUS (TCP - HTTP/WS). Without nginx2 you can still access COTURN on its standard port 3478.

**Comment by Novienzi** [comment]
Yes, I am sure. And I already change the singapore IP to Australia's either, but still got the same error.

**Comment by gjovanov** [comment]
The error `bind failed: Cannot assign requested address` clearly tells you that it cannot connect to the specified IP address. It might be that your IP is not properly assigned or the port 443 is used by some other process. Try `lsof`.

Btw starting the whole stack via `docker-compose` requires you, that everything is configured properly for your host infrastructure (firewall, networking, etc). Setting you host infra is beyond of scope of this project.

Hence, I suggest you try first starting all services, one by one (instead via docker-compose), as described in:

- https://github.com/gjovanov/roomler/tree/master/docs

In this order:
1. janus
2. coturn
3. mongo
4. redis
5. roomler
6. nginx

You can use `docker logs` to see the output of each individual service and identify potential errors.

**Comment by Novienzi** [comment]
Hi, I have tried run one by one and still got this error. And then I try another way to run the Nginx outside the docker (without docker) and now its already run but I confused why the port 3000 is connected as API and UI either but the problem is UI cant running because cant connects with the API. would you mind to help me?

**Comment by gjovanov** [comment]
In development mode, we separate the UI (port 3000) and API (port 3001) for the convenience sake only... E.g. if we make changes in the API during development, we don't want to wait for the whole UI to rebuild and vice versa... But in production mode, both UI and API are accessible on port (3000) and 3001 is not used.
