### ISSUE TITLE
Cant Join the Conference Because of No Camera on the Device

### ISSUE THREAD

**Issue by Novienzi** [gjovanov/roomler#12]
![image](https://user-images.githubusercontent.com/72146793/105837809-ca49cc80-6001-11eb-95bf-7705cd363b8a.png)

I can't join the conference because my device has no built-in camera. Thank you.

**Comment by gjovanov** [comment]
Tnx for reporting...

At the moment, I'm quite busy with other activities. Will have more time after a week or two to have a look at it.

However, you are more than welcome to submit a PR to fix this in `join-dialog.vue` in `await navigator.mediaDevices.getUserMedia` if `!self.media.video.device` to pass video: false. The same needs to be done for audio.

Are you willing ro submit PR for it?

**Comment by gjovanov** [comment]
Hey @Novienzi ,
I pushed a fix that allows users without Camera/Microphone to join the conference.

Pls test it and if it works close the issue.

If you encounter an issue, let me know.

**Comment by Novienzi** [comment]
Okay, I'll test it. Thanks for your response.

**Comment by gjovanov** [comment]
Any update on this one @Novienzi ?

**Comment by gjovanov** [comment]
I haven't received any feedback from you. Closing...

**Comment by Novienzi** [comment]
Hey, thanks a lot. Now, I can join the conference and try the features. Can I have a question about the streaming system in roomler? It doesn't use janus plugin streaming, does it?

**Comment by gjovanov** [comment]
Roomler only talks to videroom & SIP janus plugins. No streaming at the moment...

**Comment by Novienzi** [comment]
Okey, then how the screen share work then, I think at first it using a streaming plugin but when I look closely you use a videoroom plugin, right? And if you don't mind can you explain to me the SIP usage here? Thanks a lot,
