### ISSUE TITLE
"npm ERR! Maximum call stack size exceeded" while I run ./script/build.sh

### ISSUE THREAD

**Issue by yxqyrh** [gjovanov/roomler#18]
#0 2963.4 Cloning into 'roomler'...
#0 3060.2 sh: 1: node-gyp-build: Permission denied
#0 3060.4 npm ERR! Maximum call stack size exceeded
#0 3060.5 
#0 3060.5 npm ERR! A complete log of this run can be found in:
#0 3060.5 npm ERR!     /root/.npm/_logs/2023-02-15T08_35_35_506Z-debug.log
#0 3060.5 Install for [ 'lerna@latest' ] failed with code 1

**Comment by gjovanov** [comment]
It seems that you don't have acces to some folder (`Permission denied`)

**Comment by yxqyrh** [comment]
> It seems that you don't have acces to some folder (`Permission denied`)

thank you for you reply.this problem occur inside docker image ,I  changed base image from  14.5.0-buster-slim to 16.0.0-buster-slim in Dockerfile and it seemed to be resolved
