### ISSUE TITLE
bootstrap 

### ISSUE THREAD

**Issue by interfaith** [gjovanov/roomler#19]
/roomler$ npx lerna bootstrap
Need to install the following packages:
  lerna@7.2.0
Ok to proceed? (y) y

ERR! bootstrap The "bootstrap" command was removed by default in v7, and is no longer maintained.

**Comment by interfaith** [comment]
must use older node ?

**Comment by gjovanov** [comment]
in root `package.json`, you can see that we are using `"lerna": "^3.22.1",` so try installing that version.

**Comment by interfaith** [comment]
npx ***@***.*** bootstrap --scope roomler.ui

yes it worked !
