### ISSUE TITLE
Tutorial how to get started

### ISSUE THREAD

**Issue by isundaniyal** [gjovanov/roomler#5]
Roomler is great apps... but I still get a lot of errors during installation.

Please provide us tutorial on how to get started from a new build OS (exp Centos 7 minimal). for example: via youtube video

Thank you

**Comment by gjovanov** [comment]
Hi @isundaniyal,
video tutorial is great idea.

However, given the priorities, activities and timelines on my plate, I might not be able to do it any soon. But totally agree with you, that it would be useful to have such tutorial.

In the meanwhile, if you have any specific step where you get stuck and error messages you are encountering, I might be able to help you out with it.

In addition, pls note that Roomler app requires that you have some pre-knowledge about Janus, Docker, Mongo, etc before it can be installed. Providing basic knowledge about those technologies is out of scope of this project.

So pls let me know if you have some specific issue during the setup.

**Comment by gjovanov** [comment]
Closing as this is not an issue. Feel free to open in case of any issue encountered.
