### ISSUE TITLE
How if I want to take the API only?

### ISSUE THREAD

**Issue by Novienzi** [gjovanov/roomler#9]
can I take the API only from roomler? But I am getting confused when seeing the roomler.config dependencies. Thanks

**Comment by gjovanov** [comment]
Hi @Novienzi ,
u cannot take only roomler.api. All /packages  are layers of a single app roomler.

In other words, multiple packages are managed via 
https://github.com/lerna/lerna as a single app.

All you need yo do is run:

`npx lerna boostrap`

in the root folder and it will install

**Comment by Novienzi** [comment]
okay, thank you for the response. But can I use the API for another application if in case I want to develop this app on mobile?

**Comment by gjovanov** [comment]
Yes, you can easily develop a new UI package e.g. a react native that will talk to roomler.api.

**Comment by Novienzi** [comment]
Okey, thanks a lot.

**Comment by Novienzi** [comment]
Then, would you mind if describe the API schema for general like who is able to create room, or where I have to go (which API) after login to create room, etc? 

Thank you

**Comment by gjovanov** [comment]
also Swagger is available at: `https://roomler.live/docs`

**Comment by gjovanov** [comment]
Closing...
